import React, {useEffect} from 'react'
import { useCart } from "../../utils/hooks/useCart"
import orderApi from "../../utils/api/orderApi";
import orderItemApi from '../../utils/api/orderItemApi';
import { useUser } from '../../utils/hooks/useUser';
function OrderSummary({ onPaymentComplete }) {
    const { subtotal, delivery, discount, defaultTotal, clearCart, items } = useCart();
    console.log(items);
    const { currentUser } = useUser();
    const onApprove = async () => {
        const order = {
            DateTime: new Date().toISOString(),
            TotalPrice: defaultTotal,
            Status: 0,
            UserID: currentUser.userID
        };
        console.log('Order details:', order);
        const newOrder = await orderApi.createOrder(order);
        console.log('New Order details:', newOrder);

        // Add each item in the order to the OrderItems table
        for (const item of items) {
            const orderItem = {
                OrderItemID: 0, // This should be auto-generated by the server
                ProductID: item.product.productID, // Include the ProductID
                Quantity: item.quantity,
                OrderID: newOrder.orderID,
            };
            console.log(orderItem);
            await orderItemApi.addOrderItem(orderItem);
        }

        clearCart();
        alert(`Your order has been confirmed.`);
        onPaymentComplete();
    };
    return (
    <div className='order-summary'>
        <div className="space-between">
            <p>Subtotal</p>
            <p>{subtotal}</p>
        </div>
        {discount > 0 && (
              <div className="space-between">
                <p>Discount</p>
                <p>-10%</p>
              </div>
        )}
        <div className="space-between">
            <p>Delivery</p>
            <p>{delivery}</p>
        </div>
        <div className="line"></div>
        <div className="space-between bold">
            <p>Total</p>
            <p>{defaultTotal}</p>
        </div>
          <button onClick={onApprove}>Confirm</button>
    </div>
  )
}

export default OrderSummary